"""empty message

Revision ID: f70c6e87efbe
Revises: 1af0441589fe
Create Date: 2021-03-30 13:25:38.364229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70c6e87efbe'
down_revision = '1af0441589fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('type', sa.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
